<?php


namespace Gravity\CoreBundle\Field\Boolean;

use Gravity\Component\Field\AbstractFieldDefinition;

/**
 * Class BooleanField
 *
 * @package gravity\CoreBundle\Field\Boolean
 * @author Andy Thorne <contrabandvr@gmail.com>
 */
class BooleanField extends AbstractFieldDefinition
{
    /**
     * Get the identifier name of the field. This must be a unique name and contain only alphanumeric, underscores (_)
     * and period (.) characters in the format field.<plugin>.<type>
     *
     * @return string
     */
    public function getName()
    {
        return 'boolean';
    }

    /**
     * A friendly text label for the field widget
     *
     * @return string
     */
    public function getLabel()
    {
        return 'A boolean field';
    }

    /**
     * Get the description of the field
     *
     * @return string
     */
    public function getDescription()
    {
        return 'A field that will either equate to true or false';
    }

    /**
     * Get the entity class name for this field
     *
     * @return string
     */
    public function getEntityClass()
    {
        return 'Gravity\CoreBundle\Entity\FieldBoolean';
    }

    public function getDefaultWidget()
    {
        parent::getDefaultWidget(); // TODO: Change the autogenerated stub
    }
}
