<?php

namespace Gravity\FileBundle\File\Exception;

/**
 * Class FileUploadFailedException
 *
 * @package Gravity\FileBundle\File\Exception
 * @author  Andy Thorne <contrabandvr@gmail.com>
 */
class FileUploadFailedException extends FileUploadException
{
    public function __construct($type, \Exception $previous = null)
    {
        parent::__construct("File Upload Failed", $type, $previous); // TODO: Change the autogenerated stub
    }
}
