<?php

namespace Gravity\FileBundle\File\Exception;

/**
 * Class FileUploadFailedException
 *
 * @package Gravity\FileBundle\File\Exception
 * @author  Andy Thorne <contrabandvr@gmail.com>
 */
class FileUploadExtensionDeniedException extends FileUploadException
{
    public function __construct(\Exception $previous = null)
    {
        parent::__construct("File upload type was invalid", null, $previous); // TODO: Change the autogenerated stub
    }
}
