parameters:
  gravity_node.doctrine.node_listener.class:  Gravity\NodeBundle\Doctrine\EventListener\NodeEventListener
  gravity_node.doctrine.content_type_listener.class:  Gravity\NodeBundle\Doctrine\EventListener\ContentTypeEventListener

services:

  #
  # Entity Definitions
  gravity_node.entity.node:
    class: Gravity\NodeBundle\Gravity\Entity\NodeEntity
    tags:
      - { name: gravity.entity }

  #
  # Doctrine - Map node listener
  gravity_node.doctrine.node_listener:
    class: %gravity_node.doctrine.node_listener.class%
    arguments:
      - @service_container
    tags:
      - { name: doctrine.event_subscriber }

  #
  # Entities
  gravity.entity_service.content_type:
    class: Gravity\NodeBundle\Entity\Service\ContentTypeEntityService
    arguments:
      - @doctrine.orm.default_entity_manager

  gravity.entity_service.node:
    class: Gravity\NodeBundle\Entity\Service\NodeEntityService
    arguments:
      - @doctrine.orm.default_entity_manager



  #
  # Forms - field collection
  gravity_node.form.type.gravity_node:
    class: Gravity\NodeBundle\Form\NodeForm
    arguments:
        - @gravity_cms.field_manager
    tags:
        - { name: form.type, alias: gravity_node }

  gravity_node.form.type.gravity_node_content_type:
    class: Gravity\NodeBundle\Form\ContentTypeForm
    tags:
        - { name: form.type, alias: gravity_node_content_type }

  gravity_node.form.type.field_content_type_field_view_change:
    class: Gravity\NodeBundle\Form\ContentTypeFieldViewChangeForm
    arguments:
        - @gravity_cms.field_manager
    tags:
        - { name: form.type, alias: gravity_node_content_type_field_view_change }

  #
  # Configuration events
  gravity_node.event_listener.configuration:
    class: Gravity\NodeBundle\EventListener\ConfigurationEventSubscriber
    arguments:
      - @gravity_cms.config_manager
      - @doctrine.orm.default_entity_manager
    tags:
        - { name: kernel.event_subscriber }

  #
  # Node routing manager
  gravity_node.node_route_manager:
    class: Gravity\NodeBundle\Router\NodeRouterManager
    arguments:
      - @gravity_cms.config_manager

  gravity_node.routing.node_path_processor:
    class: Gravity\NodeBundle\Router\PathProcessor\NodePathProcessor
    tags:
      - { name: gravity.node.path_processor }

  #
  # Views
#  gravity_node.view.node:
#    class: Gravity\NodeBundle\View\NodeView
#    tags:
#      - { name: gravity.view_type }
#
#  gravity_node.view.block.content:
#    class: Gravity\NodeBundle\View\Block\ContentBlock
#    tags:
#      - { name: gravity.view.block }
