api_content_type_routing:
  type:         rest
  resource:     Gravity\NodeBundle\Controller\Api\RoutingController
  prefix: /node

api_node:
  type:         rest
  resource:     Gravity\NodeBundle\Controller\Api\NodeController
  prefix: /node
