services:

  #
  # Field
  gravity.field.boolean:
    class: Gravity\CoreBundle\Field\Boolean\BooleanField
    tags:
      - { name: gravity.field }

  #
  # Widgets
  gravity.field.boolean.widget.checkbox:
    class: Gravity\CoreBundle\Field\Boolean\Widget\Checkbox\CheckboxWidget
    tags:
      - { name: gravity.field.widget }

  gravity.field.boolean.widget.select:
    class: Gravity\CoreBundle\Field\Boolean\Widget\Select\SelectWidget
    tags:
      - { name: gravity.field.widget }

  #
  # Displays
#  gravity_node.field.boolean.display:
#    class: Gravity\CoreBundle\Field\Text\Display\TextFieldDisplay
#    tags:
#      - { name: gravity.field.display }
